### ISSUE TITLE
content.matchAll is not a function

### ISSUE THREAD

**Issue by ferozed** [pklaschka/ssblc#129]
Running this on my docs folder, I get an error.

```
$ ssblc
Running at http://localhost:3000

0/0	 Checking link:  http://localhost:3000/
Something didn't quite work as expected:  content.matchAll is not a function
ferozed:~/stash/ops/docs (main)
```

Here is my directory listing

```
$ ls
README.md			_sidebar.md			apple-touch-icon.png		index.html
_coverpage.md			alpha				favicon-16x16.png		site.webmanifest
_footer.md			android-chrome-192x192.png	favicon-32x32.png		v1
_navbar.md			android-chrome-512x512.png	favicon.ico
```

**Comment by pklaschka** [comment]
Sorry for the late response.

While I can't be sure, my best guess would be that you're using a NodeJS version smaller than v12, where `string.matchAll` isn't supported yet (cf. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll#browser_compatibility).

I'll specify this in the package so that a warning appears when installing it with an older version of `node`.
